version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: streaming
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 711179
      POSTGRES_DB: postgres

volumes:
  postgres-disk: